### ISSUE TITLE
Do you have a static IP?

### ISSUE THREAD

**Issue by captncraig** [captn3m0/lightsaber#5]
A root CNAME record is generally a bad idea. It often prevents you from having NS/MX or any other records at the root name. 

An A record would be much preferred, although it allows less flexibility if you move the service. Do you have an ip address that is unlikely to change?

**Comment by captn3m0** [comment]
The box that is currently running this service does not have a static IP. However, I do have another box that can host this (Digital Ocean with a floating IP)

I'll likely run a second instance of lightsaber there, with no support for the yml (so I don't have to worry about deploys)

**Comment by stp-ip** [comment]
Google offers a static anycast IP with the http(s) global load balancer. This might be interesting as a static endpoint. https://cloud.google.com/load-balancing/

**Comment by captn3m0** [comment]
Will be migrating lightsaber to my DO droplet this weekend
